
class DataIngestionArtifacts:...
class DataValidationArtifacts:...
class DataTransformationArtifacts:...
class ModelTrainerArtifacts:...
class ModelEvaluationArtifacts:...
class ModelPusherArtifacts:...